/*
 * File: app/model/AirportInfo.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.AirportInfo', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'id',
            type: 'int'
        },
        {
            name: 'beginTime',
            type: 'string'
        },
        {
            name: 'endTime',
            type: 'string'
        },
        {
            name: 'airNo',
            type: 'string'
        },
        {
            name: 'airCom',
            type: 'string'
        },
        {
            name: 'terminal',
            type: 'string'
        },
        {
            name: 'destination',
            type: 'string'
        },
        {
            name: 'counter',
            type: 'string'
        },
        {
            name: 'status',
            type: 'string'
        },
        {
            name: 'subAirNo',
            type: 'string'
        }
    ]
});